CREATE DATABASE manager;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    age INTEGER,
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;